spring:
  application:
    name: ms-transacciones
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}
  datasource:
    url: ${DB_URL:jdbc:mysql://mysql:3306/bank_cloud?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
    username: ${DB_USER:bank}
    password: ${DB_PASSWORD:bank123}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.duoc.bank.transacciones.event.RetiroEvent
        spring.json.use.type.headers: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://keycloak:8080/realms/banco/protocol/openid-connect/certs}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: health,info
